,Unnamed: 0,Unnamed: 0.1,target1,doc1,origin,Unnamed: 0,Unnamed: 0.1,target2,doc2,origin
19,19.0,19.0,1.0,Home Assistant OS,home-assistant_core_issues_52801,19.0,19.0,0.0,Home Assistant OS,home-assistant_core_issues_52801
23,23.0,23.0,0.0,Modbus,home-assistant_core_issues_52801,23.0,23.0,1.0,Modbus,home-assistant_core_issues_52801
201,201.0,11.0,0.0,apt,ansible_ansible_issues_75381,201.0,11.0,1.0,apt,ansible_ansible_issues_75381
466,466.0,9.0,0.0,# try using different optimizers and different optimizer configs,keras-team_keras_issues_1898,466.0,9.0,1.0,# try using different optimizers and different optimizer configs,keras-team_keras_issues_1898
472,472.0,1.0,1.0,"_Original ticket http://projects.scipy.org/numpy/ticket/564 on 2007-08-06 by trac user DrIdiot, assigned to unknown._",numpy_numpy_issues_1162,472.0,1.0,0.0,"_Original ticket http://projects.scipy.org/numpy/ticket/564 on 2007-08-06 by trac user DrIdiot, assigned to unknown._",numpy_numpy_issues_1162
519,519.0,10.0,0.0,->[[0.2]],numpy_numpy_issues_5375,519.0,10.0,1.0,->[[0.2]],numpy_numpy_issues_5375
562,562.0,40.0,1.0,hosts,ansible_ansible_issues_23711,562.0,40.0,0.0,hosts,ansible_ansible_issues_23711
712,712.0,10.0,0.0,**Description of problem:**,home-assistant_core_issues_2279,712.0,10.0,1.0,**Description of problem:**,home-assistant_core_issues_2279
713,713.0,11.0,0.0,"After upgrade to version 0.21.0, initially Home Assistant seems to function, but when requesting the History, this will result a call to `/api/history/period/2016-6-11`, returning a 500 error with content:",home-assistant_core_issues_2279,713.0,11.0,1.0,"After upgrade to version 0.21.0, initially Home Assistant seems to function, but when requesting the History, this will result a call to `/api/history/period/2016-6-11`, returning a 500 error with content:",home-assistant_core_issues_2279
750,750.0,48.0,0.0,Yaml does not seem relevant,home-assistant_core_issues_2279,750.0,48.0,1.0,Yaml does not seem relevant,home-assistant_core_issues_2279
843,843.0,24.0,0.0,1. Wink,home-assistant_core_issues_2690,843.0,24.0,1.0,1. Wink,home-assistant_core_issues_2690
844,844.0,25.0,0.0,2. IFTTT,home-assistant_core_issues_2690,844.0,25.0,1.0,2. IFTTT,home-assistant_core_issues_2690
845,845.0,26.0,0.0,3. LIFX,home-assistant_core_issues_2690,845.0,26.0,1.0,3. LIFX,home-assistant_core_issues_2690
853,853.0,34.0,0.0,**Additional info:**,home-assistant_core_issues_2690,853.0,34.0,1.0,**Additional info:**,home-assistant_core_issues_2690
892,892.0,36.0,1.0,Home Assistant Container,home-assistant_core_issues_55993,892.0,36.0,0.0,Home Assistant Container,home-assistant_core_issues_55993
965,965.0,6.0,0.0,openssl_csr module,ansible_ansible_issues_33676,965.0,6.0,1.0,openssl_csr module,ansible_ansible_issues_33676
1057,1057.0,28.0,1.0,and these a few lines from OZW.log:,home-assistant_core_issues_7943,1057.0,28.0,0.0,and these a few lines from OZW.log:,home-assistant_core_issues_7943
1102,1102.0,34.0,0.0,`ansible -m ping -i hosts all`,ansible_ansible_issues_13960,1102.0,34.0,1.0,`ansible -m ping -i hosts all`,ansible_ansible_issues_13960
1103,1103.0,35.0,1.0,should start successfully,ansible_ansible_issues_13960,1103.0,35.0,0.0,should start successfully,ansible_ansible_issues_13960
1146,1146.0,9.0,1.0,-->,home-assistant_core_issues_21644,1146.0,9.0,0.0,-->,home-assistant_core_issues_21644
1162,1162.0,25.0,1.0,Docker on Ubuntu 18.04 LXC on Ubuntu 18.04,home-assistant_core_issues_21644,1162.0,25.0,0.0,Docker on Ubuntu 18.04 LXC on Ubuntu 18.04,home-assistant_core_issues_21644
1164,1164.0,27.0,1.0,**Component/platform:**,home-assistant_core_issues_21644,1164.0,27.0,0.0,**Component/platform:**,home-assistant_core_issues_21644
1253,1253.0,9.0,1.0,> callable: callable with input two 1d ndarrays returning a float. Note that the returned matrix from corr have 1 along the diagonals and will be symmetric of the callable's behavior.,pandas-dev_pandas_issues_44671,1253.0,9.0,0.0,> callable: callable with input two 1d ndarrays returning a float. Note that the returned matrix from corr have 1 along the diagonals and will be symmetric of the callable's behavior.,pandas-dev_pandas_issues_44671
1296,1296.0,2.0,1.0,**Kubernetes version** : not used,apache_airflow_issues_14189,1296.0,2.0,0.0,**Kubernetes version** : not used,apache_airflow_issues_14189
1299,1299.0,5.0,1.0,- **Cloud provider or hardware configuration**: MacBook Pro,apache_airflow_issues_14189,1299.0,5.0,0.0,- **Cloud provider or hardware configuration**: MacBook Pro,apache_airflow_issues_14189
1480,1480.0,29.0,1.0,- Home Assistant Core release with the issue: 0.116.2,home-assistant_core_issues_41625,1480.0,29.0,0.0,- Home Assistant Core release with the issue: 0.116.2,home-assistant_core_issues_41625
1482,1482.0,31.0,1.0,- Operating environment (OS/Container/Supervised/Core): HassOS 4.13 in VirtualBox on a Mac Mini,home-assistant_core_issues_41625,1482.0,31.0,0.0,- Operating environment (OS/Container/Supervised/Core): HassOS 4.13 in VirtualBox on a Mac Mini,home-assistant_core_issues_41625
1635,1635.0,14.0,0.0,aws_ec2,ansible_ansible_issues_63895,1635.0,14.0,1.0,aws_ec2,ansible_ansible_issues_63895
1709,1709.0,15.0,1.0,Home Assistant OS,home-assistant_core_issues_53349,1709.0,15.0,0.0,Home Assistant OS,home-assistant_core_issues_53349
1721,1721.0,27.0,0.0,_No response_,home-assistant_core_issues_53349,1721.0,27.0,1.0,_No response_,home-assistant_core_issues_53349
1836,1836.0,4.0,0.0,"when I use this, it not working and in cmd show",scikit-learn_scikit-learn_issues_8654,1836.0,4.0,1.0,"when I use this, it not working and in cmd show",scikit-learn_scikit-learn_issues_8654
1867,1867.0,8.0,0.0,Exception while reading event:,home-assistant_core_issues_58897,1867.0,8.0,1.0,Exception while reading event:,home-assistant_core_issues_58897
1868,1868.0,9.0,0.0,Traceback (most recent call last):,home-assistant_core_issues_58897,1868.0,9.0,1.0,Traceback (most recent call last):,home-assistant_core_issues_58897
1883,1883.0,24.0,1.0,Home Assistant Supervised,home-assistant_core_issues_58897,1883.0,24.0,0.0,Home Assistant Supervised,home-assistant_core_issues_58897
1887,1887.0,28.0,0.0,HomeConnect,home-assistant_core_issues_58897,1887.0,28.0,1.0,HomeConnect,home-assistant_core_issues_58897
1950,1950.0,20.0,0.0,Docker-Compose,apache_airflow_issues_18940,1950.0,20.0,1.0,Docker-Compose,apache_airflow_issues_18940
2000,2000.0,70.0,0.0,Dockerfile:,apache_airflow_issues_18940,2000.0,70.0,1.0,Dockerfile:,apache_airflow_issues_18940
2002,2002.0,72.0,0.0,FROM python:3.8,apache_airflow_issues_18940,2002.0,72.0,1.0,FROM python:3.8,apache_airflow_issues_18940
2009,2009.0,79.0,0.0,requirements.txt:,apache_airflow_issues_18940,2009.0,79.0,1.0,requirements.txt:,apache_airflow_issues_18940
2046,2046.0,116.0,0.0,The above exception was the direct cause of the following exception:,apache_airflow_issues_18940,2046.0,116.0,1.0,The above exception was the direct cause of the following exception:,apache_airflow_issues_18940
2284,2284.0,5.0,0.0,dconf,ansible_ansible_issues_37303,2284.0,5.0,1.0,dconf,ansible_ansible_issues_37303
2367,2367.0,13.0,0.0,ec2_vpc_endpoint,ansible_ansible_issues_47898,2367.0,13.0,1.0,ec2_vpc_endpoint,ansible_ansible_issues_47898
2396,2396.0,11.0,1.0,_Originally posted by @Ananas120 in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/447#issuecomment-672644774_,CorentinJ_Real-Time-Voice-Cloning_issues_484,2396.0,11.0,0.0,_Originally posted by @Ananas120 in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/447#issuecomment-672644774_,CorentinJ_Real-Time-Voice-Cloning_issues_484
2445,2445.0,19.0,1.0,See also: https://sentry.zendesk.com/agent/tickets/616,getsentry_sentry_issues_2100,2445.0,19.0,0.0,See also: https://sentry.zendesk.com/agent/tickets/616,getsentry_sentry_issues_2100
2455,2455.0,3.0,1.0,#### numpy 1.13,numpy_numpy_issues_9804,2455.0,3.0,0.0,#### numpy 1.13,numpy_numpy_issues_9804
2483,2483.0,0.0,0.0,"expected activation_49 to have shape (4,) but got array with shape (2,)",keras-team_keras_issues_11490,2483.0,0.0,1.0,"expected activation_49 to have shape (4,) but got array with shape (2,)",keras-team_keras_issues_11490
2484,2484.0,1.0,0.0,Using Enhanced Data Generation,keras-team_keras_issues_11490,2484.0,1.0,1.0,Using Enhanced Data Generation,keras-team_keras_issues_11490
2519,2519.0,10.0,1.0,- AWS EC2 instance,ray-project_ray_issues_14948,2519.0,100.0,0.0,- AWS EC2 instance,ray-project_ray_issues_14948
2623,2623.0,13.0,0.0,<!--,home-assistant_core_issues_25725,2623.0,13.0,1.0,<!--,home-assistant_core_issues_25725
2632,2632.0,22.0,1.0,Docker (Synology),home-assistant_core_issues_25725,2632.0,22.0,0.0,Docker (Synology),home-assistant_core_issues_25725
2687,2687.0,77.0,1.0,"* https://github.com/home-assistant/home-assistant/issues/17410 - ""Please open a new issue if you still experience issues or think there's a bug.""",home-assistant_core_issues_25725,2687.0,77.0,0.0,"* https://github.com/home-assistant/home-assistant/issues/17410 - ""Please open a new issue if you still experience issues or think there's a bug.""",home-assistant_core_issues_25725
2688,2688.0,78.0,1.0,"* https://github.com/home-assistant/home-assistant/issues/21733 - not resolved, different platform, hint (delete cookie, restart 2X) does not work for me.",home-assistant_core_issues_25725,2688.0,78.0,0.0,"* https://github.com/home-assistant/home-assistant/issues/21733 - not resolved, different platform, hint (delete cookie, restart 2X) does not work for me.",home-assistant_core_issues_25725
2689,2689.0,79.0,1.0,* https://github.com/home-assistant/home-assistant/issues/25312 - Resolved but no explonation and still not work for me.,home-assistant_core_issues_25725,2689.0,79.0,0.0,* https://github.com/home-assistant/home-assistant/issues/25312 - Resolved but no explonation and still not work for me.,home-assistant_core_issues_25725
2702,2702.0,8.0,0.0,letsencrypt.py,ansible_ansible_issues_41873,2702.0,8.0,1.0,letsencrypt.py,ansible_ansible_issues_41873
2705,2705.0,11.0,1.0,"<!--- Paste, BELOW THIS COMMENT, verbatim output from ""ansible --version"" between quotes below -->",ansible_ansible_issues_41873,2705.0,11.0,0.0,"<!--- Paste, BELOW THIS COMMENT, verbatim output from ""ansible --version"" between quotes below -->",ansible_ansible_issues_41873
2794,2794.0,100.0,1.0,<!--- You can also paste gist.github.com links for larger files -->,ansible_ansible_issues_41873,2794.0,100.0,0.0,<!--- You can also paste gist.github.com links for larger files -->,ansible_ansible_issues_41873
2796,2796.0,102.0,1.0,##### EXPECTED RESULTS,ansible_ansible_issues_41873,2796.0,102.0,0.0,##### EXPECTED RESULTS,ansible_ansible_issues_41873
2797,2797.0,103.0,1.0,<!--- What did you expect to happen when running the steps above? -->,ansible_ansible_issues_41873,2797.0,103.0,0.0,<!--- What did you expect to happen when running the steps above? -->,ansible_ansible_issues_41873
2799,2799.0,105.0,1.0,"As there were only 28 days to expiration, it should have issued 'challenge_data'",ansible_ansible_issues_41873,2799.0,105.0,0.0,"As there were only 28 days to expiration, it should have issued 'challenge_data'",ansible_ansible_issues_41873
2801,2801.0,107.0,1.0,##### ACTUAL RESULTS,ansible_ansible_issues_41873,2801.0,107.0,0.0,##### ACTUAL RESULTS,ansible_ansible_issues_41873
2802,2802.0,108.0,1.0,<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->,ansible_ansible_issues_41873,2802.0,108.0,0.0,<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->,ansible_ansible_issues_41873
2803,2803.0,109.0,1.0,"'challenge_data' was not created because the module returns ""cert_days = 56""",ansible_ansible_issues_41873,2803.0,109.0,0.0,"'challenge_data' was not created because the module returns ""cert_days = 56""",ansible_ansible_issues_41873
2805,2805.0,111.0,1.0,<!--- Paste verbatim command output between quotes below -->,ansible_ansible_issues_41873,2805.0,111.0,0.0,<!--- Paste verbatim command output between quotes below -->,ansible_ansible_issues_41873
2993,2993.0,15.0,0.0,"<!-- Output from 'import sys, numpy; print(numpy.__version__, sys.version)' -->",numpy_numpy_issues_13554,2993.0,15.0,1.0,"<!-- Output from 'import sys, numpy; print(numpy.__version__, sys.version)' -->",numpy_numpy_issues_13554
2997,2997.0,1.0,1.0,操作步骤：,ansible_ansible_issues_68960,2997.0,1.0,0.0,操作步骤：,ansible_ansible_issues_68960
3004,3004.0,8.0,1.0,问题：,ansible_ansible_issues_68960,3004.0,8.0,0.0,问题：,ansible_ansible_issues_68960
3021,3021.0,0.0,0.0,python 3: test_to_string_truncate_indices  UnicodeEncodeError: 'ascii' codec can't encode characters in position 177-178: ordinal not in range(128),pandas-dev_pandas_issues_7247,3021.0,0.0,1.0,python 3: test_to_string_truncate_indices  UnicodeEncodeError: 'ascii' codec can't encode characters in position 177-178: ordinal not in range(128),pandas-dev_pandas_issues_7247
3063,3063.0,1.0,1.0,See also #13773.,scikit-learn_scikit-learn_issues_13789,3063.0,1.0,0.0,See also #13773.,scikit-learn_scikit-learn_issues_13789
3255,3255.0,3.0,0.0,#settings for mail,scrapy_scrapy_issues_3758,3255.0,3.0,1.0,#settings for mail,scrapy_scrapy_issues_3758
3264,3264.0,12.0,0.0,Email was sent successfully. But the following exception is thrown;,scrapy_scrapy_issues_3758,3264.0,12.0,1.0,Email was sent successfully. But the following exception is thrown;,scrapy_scrapy_issues_3758
3332,3332.0,6.0,1.0,- **OS** (e.g. from /etc/os-release): Debian 10,apache_airflow_issues_11122,3332.0,6.0,0.0,- **OS** (e.g. from /etc/os-release): Debian 10,apache_airflow_issues_11122
3334,3334.0,8.0,0.0,- **Install tools**: pip,apache_airflow_issues_11122,3334.0,8.0,1.0,- **Install tools**: pip,apache_airflow_issues_11122
3343,3343.0,17.0,1.0,From the [documentation](https://airflow.apache.org/docs/stable/configurations-ref.html#min-file-process-interval),apache_airflow_issues_11122,3343.0,17.0,0.0,From the [documentation](https://airflow.apache.org/docs/stable/configurations-ref.html#min-file-process-interval),apache_airflow_issues_11122
3353,3353.0,5.0,1.0,**Home Assistant release (`hass --version`):** 55,home-assistant_core_issues_9766,3353.0,5.0,0.0,**Home Assistant release (`hass --version`):** 55,home-assistant_core_issues_9766
3355,3355.0,7.0,1.0,**Python release (`python3 --version`):** 3.5,home-assistant_core_issues_9766,3355.0,7.0,0.0,**Python release (`python3 --version`):** 3.5,home-assistant_core_issues_9766
3435,3435.0,8.0,1.0,- Using GPU in script?: <fill in>,huggingface_transformers_issues_11642,3435.0,8.0,0.0,- Using GPU in script?: <fill in>,huggingface_transformers_issues_11642
3436,3436.0,9.0,1.0,- Using distributed or parallel set-up in script?: <fill in>,huggingface_transformers_issues_11642,3436.0,9.0,0.0,- Using distributed or parallel set-up in script?: <fill in>,huggingface_transformers_issues_11642
3480,3480.0,1.0,1.0,"_Original ticket http://projects.scipy.org/numpy/ticket/61 on 2006-04-15 by @alberts, assigned to unknown._",numpy_numpy_issues_545,3480.0,1.0,0.0,"_Original ticket http://projects.scipy.org/numpy/ticket/61 on 2006-04-15 by @alberts, assigned to unknown._",numpy_numpy_issues_545
3489,3489.0,10.0,1.0,Valgrind says:,numpy_numpy_issues_545,3489.0,10.0,0.0,Valgrind says:,numpy_numpy_issues_545
3556,3556.0,6.0,0.0,***** Running training *****,huggingface_transformers_issues_11626,3556.0,6.0,1.0,***** Running training *****,huggingface_transformers_issues_11626
3718,3718.0,16.0,1.0,Home Assistant Container,home-assistant_core_issues_60455,3718.0,16.0,0.0,Home Assistant Container,home-assistant_core_issues_60455
3722,3722.0,20.0,0.0,shelly,home-assistant_core_issues_60455,3722.0,20.0,1.0,shelly,home-assistant_core_issues_60455
3794,3794.0,14.0,0.0,gcp_compute_instance_facts,ansible_ansible_issues_51097,3794.0,14.0,1.0,gcp_compute_instance_facts,ansible_ansible_issues_51097
3810,3810.0,30.0,0.0,None,ansible_ansible_issues_51097,3810.0,30.0,1.0,None,ansible_ansible_issues_51097
3815,3815.0,35.0,1.0,Arch linux latest,ansible_ansible_issues_51097,3815.0,35.0,0.0,Arch linux latest,ansible_ansible_issues_51097
3862,3862.0,82.0,0.0,"  - msg: Invalid data passed to 'loop', it requires a list, got this instead: <built-in method items of dict object at 0x7f7bde102b40>. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup.",ansible_ansible_issues_51097,3862.0,82.0,1.0,"  - msg: Invalid data passed to 'loop', it requires a list, got this instead: <built-in method items of dict object at 0x7f7bde102b40>. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup.",ansible_ansible_issues_51097
3863,3863.0,83.0,0.0,},ansible_ansible_issues_51097,3863.0,83.0,1.0,},ansible_ansible_issues_51097
3943,3943.0,0.0,0.0,ValueError: invalid literal for int() with base 10: 'dev0',mitmproxy_mitmproxy_issues_759,3943.0,0.0,1.0,ValueError: invalid literal for int() with base 10: 'dev0',mitmproxy_mitmproxy_issues_759
4019,4019.0,61.0,0.0,"During handling of the above exception, another exception occurred:",pandas-dev_pandas_issues_42899,4019.0,61.0,1.0,"During handling of the above exception, another exception occurred:",pandas-dev_pandas_issues_42899
4145,4145.0,10.0,1.0,- Using GPU in script?: Yes,huggingface_transformers_issues_7692,4145.0,10.0,0.0,- Using GPU in script?: Yes,huggingface_transformers_issues_7692
4146,4146.0,11.0,1.0,- Using distributed or parallel set-up in script?: Distributed,huggingface_transformers_issues_7692,4146.0,11.0,0.0,- Using distributed or parallel set-up in script?: Distributed,huggingface_transformers_issues_7692
4196,4196.0,61.0,1.0,1.,huggingface_transformers_issues_7692,4196.0,61.0,0.0,1. ,huggingface_transformers_issues_7692
4197,4197.0,62.0,1.0,2.,huggingface_transformers_issues_7692,4197.0,62.0,0.0,2.,huggingface_transformers_issues_7692
4198,4198.0,63.0,1.0,3.,huggingface_transformers_issues_7692,4198.0,63.0,0.0,3.,huggingface_transformers_issues_7692
4239,4239.0,104.0,0.0,Function call stack:,huggingface_transformers_issues_7692,4239.0,104.0,1.0,Function call stack:,huggingface_transformers_issues_7692
4240,4240.0,105.0,0.0,distributed_prediction_steps,huggingface_transformers_issues_7692,4240.0,105.0,1.0,distributed_prediction_steps,huggingface_transformers_issues_7692
4565,4565.0,6.0,1.0,Error:,huggingface_transformers_issues_1032,4565.0,6.0,0.0,Error:,huggingface_transformers_issues_1032
4582,4582.0,5.0,0.0,icinga2_feature,ansible_ansible_issues_39830,4582.0,5.0,1.0,icinga2_feature,ansible_ansible_issues_39830
4737,4737.0,15.0,1.0,Home Assistant OS,home-assistant_core_issues_64824,4737.0,15.0,0.0,Home Assistant OS,home-assistant_core_issues_64824
4789,4789.0,18.0,1.0,Home Assistant OS,home-assistant_core_issues_56787,4789.0,18.0,0.0,Home Assistant OS,home-assistant_core_issues_56787
4793,4793.0,22.0,0.0,daikin,home-assistant_core_issues_56787,4793.0,22.0,1.0,daikin,home-assistant_core_issues_56787
4899,4899.0,1.0,1.0,"_Original ticket http://projects.scipy.org/numpy/ticket/1775 on 2011-03-18 by trac user borisaqua, assigned to unknown._",numpy_numpy_issues_2368,4899.0,1.0,0.0,"_Original ticket http://projects.scipy.org/numpy/ticket/1775 on 2011-03-18 by trac user borisaqua, assigned to unknown._",numpy_numpy_issues_2368
5168,5168.0,35.0,1.0,hass.io in VMWare,home-assistant_core_issues_24466,5168.0,35.0,0.0,hass.io in VMWare,home-assistant_core_issues_24466
5238,5238.0,40.0,1.0,Home Assistant OS,home-assistant_core_issues_49061,5238.0,40.0,0.0,Home Assistant OS,home-assistant_core_issues_49061
5242,5242.0,44.0,0.0,Zwave.js,home-assistant_core_issues_49061,5242.0,44.0,1.0,Zwave.js,home-assistant_core_issues_49061
5277,5277.0,22.0,0.0,"Schedule from queries table: `{""interval"": 300, ""until"": null, ""day_of_week"": null, ""time"": null}`",getredash_redash_issues_3341,5277.0,22.0,1.0,"Schedule from queries table: `{""interval"": 300, ""until"": null, ""day_of_week"": null, ""time"": null}`",getredash_redash_issues_3341
5536,5536.0,26.0,1.0,- OS and Python version: [e.g. Linux/Python 3.8.5],psf_black_issues_1663,5536.0,26.0,0.0,- OS and Python version: [e.g. Linux/Python 3.8.5],psf_black_issues_1663
5573,5573.0,22.0,1.0,- Home Assistant Core release with the issue: HassOS 4.15,home-assistant_core_issues_42983,5573.0,22.0,0.0,- Home Assistant Core release with the issue: HassOS 4.15,home-assistant_core_issues_42983
5575,5575.0,24.0,1.0,- Operating environment (OS/Container/Supervised/Core):  FreeNAS (freebsd) VM,home-assistant_core_issues_42983,5575.0,24.0,0.0,- Operating environment (OS/Container/Supervised/Core):  FreeNAS (freebsd) VM,home-assistant_core_issues_42983
5620,5620.0,8.0,1.0,System Health,home-assistant_core_issues_42505,5620.0,8.0,0.0,System Health,home-assistant_core_issues_42505
5645,5645.0,33.0,1.0,Lates working version p.116,home-assistant_core_issues_42505,5645.0,33.0,0.0,Lates working version p.116,home-assistant_core_issues_42505
5690,5690.0,15.0,0.0,docs.ansible.com,ansible_ansible_issues_46122,5690.0,15.0,1.0,docs.ansible.com,ansible_ansible_issues_46122
5815,5815.0,1.0,0.0,`repr(request)` raises,pallets_flask_issues_778,5815.0,1.0,1.0,`repr(request)` raises,pallets_flask_issues_778
5939,5939.0,23.0,0.0,iosxr_command,ansible_ansible_issues_59512,5939.0,23.0,1.0,iosxr_command,ansible_ansible_issues_59512
5940,5940.0,24.0,0.0,communicate,ansible_ansible_issues_59512,5940.0,24.0,1.0,communicate,ansible_ansible_issues_59512
5941,5941.0,25.0,0.0,Connection,ansible_ansible_issues_59512,5941.0,25.0,1.0,Connection,ansible_ansible_issues_59512
6041,6041.0,0.0,0.0,topics/contributing/,encode_django-rest-framework_issues_5791,6041.0,0.0,1.0,topics/contributing/,encode_django-rest-framework_issues_5791
6059,6059.0,0.0,0.0,PATH invaild,psf_black_issues_240,6059.0,0.0,1.0,PATH invaild,psf_black_issues_240
6060,6060.0,1.0,0.0,Usage: black [OPTIONS] [SRC]...,psf_black_issues_240,6060.0,1.0,1.0,Usage: black [OPTIONS] [SRC]...,psf_black_issues_240
6079,6079.0,15.0,1.0,Homekit Controller,home-assistant_core_issues_25519,6079.0,15.0,0.0,Homekit Controller,home-assistant_core_issues_25519
6109,6109.0,5.0,0.0,module `dynamodb_table`,ansible_ansible_issues_25009,6109.0,5.0,1.0,module `dynamodb_table`,ansible_ansible_issues_25009
6174,6174.0,34.0,1.0,System environment variables:,pypa_pipenv_issues_2990,6174.0,34.0,0.0,System environment variables:,pypa_pipenv_issues_2990
6253,6253.0,113.0,1.0,Pipenv–specific environment variables:,pypa_pipenv_issues_2990,6253.0,113.0,0.0,Pipenv–specific environment variables:,pypa_pipenv_issues_2990
6257,6257.0,117.0,1.0,Debug–specific environment variables:,pypa_pipenv_issues_2990,6257.0,117.0,0.0,Debug–specific environment variables:,pypa_pipenv_issues_2990
6827,6827.0,26.0,1.0,Ubuntu Xenial and OSX Sierra,ansible_ansible_issues_26485,6827.0,26.0,0.0,Ubuntu Xenial and OSX Sierra,ansible_ansible_issues_26485
6828,6828.0,27.0,0.0,-->,ansible_ansible_issues_26485,6828.0,27.0,1.0,-->,ansible_ansible_issues_26485
6862,6862.0,61.0,0.0,`adhoc-1`,ansible_ansible_issues_26485,6862.0,61.0,1.0,`adhoc-1`,ansible_ansible_issues_26485
6866,6866.0,65.0,0.0,`adhoc-2`,ansible_ansible_issues_26485,6866.0,65.0,1.0,`adhoc-2`,ansible_ansible_issues_26485
6870,6870.0,69.0,0.0,`playbook-1`,ansible_ansible_issues_26485,6870.0,69.0,1.0,`playbook-1`,ansible_ansible_issues_26485
6878,6878.0,77.0,0.0,`adhoc-1 & adhoc-2`,ansible_ansible_issues_26485,6878.0,77.0,1.0,`adhoc-1 & adhoc-2`,ansible_ansible_issues_26485
6885,6885.0,84.0,0.0,`playbook-1`,ansible_ansible_issues_26485,6885.0,84.0,1.0,`playbook-1`,ansible_ansible_issues_26485
6904,6904.0,103.0,0.0,`adhoc-1`,ansible_ansible_issues_26485,6904.0,103.0,1.0,`adhoc-1`,ansible_ansible_issues_26485
6912,6912.0,111.0,0.0,<!--- Paste verbatim command output between quotes below -->,ansible_ansible_issues_26485,6912.0,111.0,1.0,<!--- Paste verbatim command output between quotes below -->,ansible_ansible_issues_26485
6914,6914.0,113.0,0.0,Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_ping.ps1,ansible_ansible_issues_26485,6914.0,113.0,1.0,Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_ping.ps1,ansible_ansible_issues_26485
6934,6934.0,9.0,0.0,**POST**,tornadoweb_tornado_issues_852,6934.0,9.0,1.0,**POST**,tornadoweb_tornado_issues_852
6937,6937.0,12.0,0.0,**GET**,tornadoweb_tornado_issues_852,6937.0,12.0,1.0,**GET**,tornadoweb_tornado_issues_852
6961,6961.0,8.0,0.0,virtualenv,home-assistant_core_issues_22219,6961.0,8.0,1.0,virtualenv,home-assistant_core_issues_22219
7077,7077.0,15.0,1.0,Home Assistant OS,home-assistant_core_issues_63655,7077.0,15.0,0.0,Home Assistant OS,home-assistant_core_issues_63655
7081,7081.0,19.0,0.0,?,home-assistant_core_issues_63655,7081.0,19.0,1.0,?,home-assistant_core_issues_63655
7085,7085.0,23.0,0.0,-,home-assistant_core_issues_63655,7085.0,23.0,1.0,-,home-assistant_core_issues_63655
7270,7270.0,12.0,0.0,vmware_object_role_permission,ansible_ansible_issues_53164,7270.0,12.0,1.0,vmware_object_role_permission,ansible_ansible_issues_53164
7396,7396.0,12.0,0.0,climate/generic_thermostat,home-assistant_core_issues_12120,7396.0,12.0,1.0,climate/generic_thermostat,home-assistant_core_issues_12120
7441,7441.0,9.0,0.0,influxdb,home-assistant_core_issues_25038,7441.0,9.0,1.0,influxdb,home-assistant_core_issues_25038
7535,7535.0,45.0,1.0,##### System information,mitmproxy_mitmproxy_issues_1783,7535.0,45.0,0.0,##### System information,mitmproxy_mitmproxy_issues_1783
7619,7619.0,77.0,0.0,This is what I get in the logs:,localstack_localstack_issues_3806,7619.0,77.0,1.0,This is what I get in the logs: ,localstack_localstack_issues_3806
7725,7725.0,11.0,0.0,pip,ansible_ansible_issues_76234,7725.0,11.0,1.0,pip,ansible_ansible_issues_76234
7762,7762.0,48.0,0.0,# Test pip role,ansible_ansible_issues_76234,7762.0,48.0,1.0,# Test pip role,ansible_ansible_issues_76234
7867,7867.0,15.0,0.0,MWAA,apache_airflow_issues_18316,7867.0,15.0,1.0,MWAA,apache_airflow_issues_18316
7997,7997.0,24.0,1.0,- Home Assistant Core release with the issue: 0.109,home-assistant_core_issues_35468,7997.0,24.0,0.0,- Home Assistant Core release with the issue: 0.109,home-assistant_core_issues_35468
7998,7998.0,25.0,1.0,- Last working Home Assistant Core release (if known): 0.108,home-assistant_core_issues_35468,7998.0,25.0,0.0,- Last working Home Assistant Core release (if known): 0.108,home-assistant_core_issues_35468
7999,7999.0,26.0,1.0,- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant (HASSIO) on Ubuntu 18.04,home-assistant_core_issues_35468,7999.0,26.0,0.0,- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant (HASSIO) on Ubuntu 18.04,home-assistant_core_issues_35468
8044,8044.0,13.0,0.0,ios_user,ansible_ansible_issues_50879,8044.0,13.0,1.0,ios_user,ansible_ansible_issues_50879
8243,8243.0,56.0,0.0,3. `localstack login`,localstack_localstack_issues_4787,8243.0,56.0,1.0,3. `localstack login`,localstack_localstack_issues_4787
8244,8244.0,57.0,0.0,4. `localstack pod push`,localstack_localstack_issues_4787,8244.0,57.0,1.0,4. `localstack pod push`,localstack_localstack_issues_4787
8276,8276.0,15.0,0.0,ecs_taskdefinition,ansible_ansible_issues_55031,8276.0,15.0,1.0,ecs_taskdefinition,ansible_ansible_issues_55031
8299,8299.0,3.0,0.0,Traceback (most recent call last):,psf_requests_issues_2120,8299.0,3.0,1.0,Traceback (most recent call last):,psf_requests_issues_2120
8333,8333.0,7.0,0.0,win_iis_virtualdirectory,ansible_ansible_issues_36060,8333.0,7.0,1.0,win_iis_virtualdirectory,ansible_ansible_issues_36060
8563,8563.0,0.0,1.0,AttributeError: 'module' object has no attribute 'TCPServer',pallets_flask_issues_2145,8563.0,0.0,0.0,AttributeError: 'module' object has no attribute 'TCPServer',pallets_flask_issues_2145
8621,8621.0,23.0,1.0,"Linux, Mac OS, any UNIX",ansible_ansible_issues_44809,8621.0,23.0,0.0,"Linux, Mac OS, any UNIX",ansible_ansible_issues_44809
8640,8640.0,3.0,1.0,* Operating System: Raspbian jessie with desktop,ageitgey_face_recognition_issues_154,8640.0,3.0,0.0,* Operating System: Raspbian jessie with desktop,ageitgey_face_recognition_issues_154
10070,10070.0,1364.0,0.0,in Holding Register 0000000000000011 is swith1 on and switch2 on,home-assistant_core_issues_37025,10070.0,1364.0,1.0,in Holding Register 0000000000000011 is swith1 on and switch2 on,home-assistant_core_issues_37025
10071,10071.0,1365.0,0.0,in Holding Register 0000000000000010 is swith1 off and switch2 on,home-assistant_core_issues_37025,10071.0,1365.0,1.0,in Holding Register 0000000000000010 is swith1 off and switch2 on,home-assistant_core_issues_37025
10196,10196.0,1.0,1.0,> Platform:raspberry pi 2 model b,home-assistant_core_issues_20908,10196.0,1.0,0.0,> Platform:raspberry pi 2 model b,home-assistant_core_issues_20908
10318,10318.0,1.0,1.0,"_Original ticket http://projects.scipy.org/numpy/ticket/1995 on 2011-12-13 by trac user O.C., assigned to unknown._",numpy_numpy_issues_2588,10318.0,1.0,0.0,"_Original ticket http://projects.scipy.org/numpy/ticket/1995 on 2011-12-13 by trac user O.C., assigned to unknown._",numpy_numpy_issues_2588
10405,10405.0,3.0,1.0,- Regression between 1.9.4 and 2.0.0rc3,ansible_ansible_issues_13745,10405.0,3.0,0.0,- Regression between 1.9.4 and 2.0.0rc3,ansible_ansible_issues_13745
10408,10408.0,6.0,1.0,# Summary:,ansible_ansible_issues_13745,10408.0,6.0,0.0,# Summary:,ansible_ansible_issues_13745
10419,10419.0,17.0,1.0,- `ansible all -l tenrtwo -i ./bootstrap -u root -m setup -vvvv` should work,ansible_ansible_issues_13745,10419.0,17.0,0.0,- `ansible all -l tenrtwo -i ./bootstrap -u root -m setup -vvvv` should work,ansible_ansible_issues_13745
10422,10422.0,20.0,1.0,# as seen in 1.9.4,ansible_ansible_issues_13745,10422.0,20.0,0.0,# as seen in 1.9.4,ansible_ansible_issues_13745
10579,10579.0,11.0,0.0,win_unzip,ansible_ansible_issues_54113,10579.0,11.0,1.0,win_unzip,ansible_ansible_issues_54113
10592,10592.0,24.0,0.0,`ansible-config dump --only-changed` returns nothing.,ansible_ansible_issues_54113,10592.0,24.0,1.0,`ansible-config dump --only-changed` returns nothing.,ansible_ansible_issues_54113
10809,10809.0,12.0,0.0,"1) Id = ""A/1"", Username = ""Abc""",getsentry_sentry_issues_12538,10809.0,12.0,1.0,"1) Id = ""A/1"", Username = ""Abc""",getsentry_sentry_issues_12538
10810,10810.0,13.0,0.0,"2) Id = ""A/2"", Username = ""Abc"" ",getsentry_sentry_issues_12538,10810.0,13.0,1.0,"2) Id = ""A/2"", Username = ""Abc"" ",getsentry_sentry_issues_12538
10811,10811.0,14.0,0.0,"3) Id = ""A/3"", Email= ""email""",getsentry_sentry_issues_12538,10811.0,14.0,1.0,"3) Id = ""A/3"", Email= ""email""",getsentry_sentry_issues_12538
10840,10840.0,16.0,0.0,none,home-assistant_core_issues_28076,10840.0,16.0,1.0,none,home-assistant_core_issues_28076
10948,10948.0,124.0,0.0,options.xml:,home-assistant_core_issues_28076,10948.0,124.0,1.0,options.xml:,home-assistant_core_issues_28076
10969,10969.0,145.0,0.0,debug log:,home-assistant_core_issues_28076,10969.0,145.0,1.0,debug log:,home-assistant_core_issues_28076
11016,11016.0,17.0,0.0,"Detected I/O inside the event loop. This is causing stability issues. Please report issue for avri doing I/O at homeassistant/components/avri/sensor.py, line 25: each_upcoming = client.upcoming_of_each()",home-assistant_core_issues_37305,11016.0,17.0,1.0,"Detected I/O inside the event loop. This is causing stability issues. Please report issue for avri doing I/O at homeassistant/components/avri/sensor.py, line 25: each_upcoming = client.upcoming_of_each()",home-assistant_core_issues_37305
11041,11041.0,42.0,1.0,- Home Assistant Core release with the issue: 0.112.0,home-assistant_core_issues_37305,11041.0,42.0,0.0,- Home Assistant Core release with the issue: 0.112.0,home-assistant_core_issues_37305
11043,11043.0,44.0,1.0,- Operating environment (OS/Container/Supervised/Core): HassOS (see above),home-assistant_core_issues_37305,11043.0,44.0,0.0,- Operating environment (OS/Container/Supervised/Core): HassOS (see above),home-assistant_core_issues_37305
11065,11065.0,1.0,0.0,Ansible 2.0 devel branch,ansible_ansible_issues_12478,11065.0,1.0,1.0,Ansible 2.0 devel branch,ansible_ansible_issues_12478
11127,11127.0,12.0,0.0,ansible-vault edit,ansible_ansible_issues_32873,11127.0,12.0,1.0,ansible-vault edit,ansible_ansible_issues_32873
11148,11148.0,33.0,0.0,None,ansible_ansible_issues_32873,11148.0,33.0,1.0,None,ansible_ansible_issues_32873
11151,11151.0,36.0,0.0,<!---,ansible_ansible_issues_32873,11151.0,36.0,1.0,<!---,ansible_ansible_issues_32873
11168,11168.0,53.0,0.0,1. ansible-vault existing_vault.yml,ansible_ansible_issues_32873,11168.0,53.0,1.0,1. ansible-vault existing_vault.yml,ansible_ansible_issues_32873
11241,11241.0,24.0,0.0,Step 44/3000 - 0.31283405731719177 steps/s,Textualize_rich_issues_304,11241.0,24.0,1.0,Step 44/3000 - 0.31283405731719177 steps/s,Textualize_rich_issues_304
11298,11298.0,1.0,1.0,install via: `conda install matplotlib -c tacaswell` (only linux-64 ATM),pandas-dev_pandas_issues_11111,11298.0,1.0,0.0,install via: `conda install matplotlib -c tacaswell` (only linux-64 ATM),pandas-dev_pandas_issues_11111
11900,11900.0,22.0,1.0,**Traceback (if applicable):**,home-assistant_core_issues_2014,11900.0,22.0,0.0,**Traceback (if applicable):**,home-assistant_core_issues_2014
11916,11916.0,7.0,1.0,`--pypi-mirror` should be treated as an extension to `project.sources`,pypa_pipenv_issues_4199,11916.0,7.0,0.0,`--pypi-mirror` should be treated as an extension to `project.sources`,pypa_pipenv_issues_4199
12024,12024.0,115.0,0.0,Contents of `Pipfile` ('/Users/tianyizhuang/Projects/dapeng/Pipfile'):,pypa_pipenv_issues_4199,12024.0,115.0,1.0,Contents of `Pipfile` ('/Users/tianyizhuang/Projects/dapeng/Pipfile'):,pypa_pipenv_issues_4199
12051,12051.0,142.0,0.0,Contents of `Pipfile.lock` ('/Users/tianyizhuang/Projects/dapeng/Pipfile.lock'):,pypa_pipenv_issues_4199,12051.0,142.0,1.0,Contents of `Pipfile.lock` ('/Users/tianyizhuang/Projects/dapeng/Pipfile.lock'):,pypa_pipenv_issues_4199
12346,12346.0,12.0,0.0,* Redash Version:  Version: 8.0.0+b32245 (a16f551e),getredash_redash_issues_5012,12346.0,12.0,1.0,* Redash Version:  Version: 8.0.0+b32245 (a16f551e),getredash_redash_issues_5012
12349,12349.0,15.0,1.0,chrome,getredash_redash_issues_5012,12349.0,15.0,0.0,chrome,getredash_redash_issues_5012
12356,12356.0,3.0,0.0,# TODO: Update this line to work with batch > 1. Right now it assumes all,keras-team_keras_issues_10011,12356.0,3.0,1.0,# TODO: Update this line to work with batch > 1. Right now it assumes all,keras-team_keras_issues_10011
12357,12357.0,4.0,0.0,#       images in a batch have the same active_class_ids,keras-team_keras_issues_10011,12357.0,4.0,1.0,#       images in a batch have the same active_class_ids,keras-team_keras_issues_10011
12388,12388.0,27.0,1.0,"**the model is still trainable, although it now expects compressed representations as targets:**",keras-team_keras_issues_1633,12388.0,27.0,0.0,"**the model is still trainable, although it now expects compressed representations as targets:**",keras-team_keras_issues_1633
12445,12445.0,10.0,0.0,nxos_l3_interface,ansible_ansible_issues_41491,12445.0,10.0,1.0,nxos_l3_interface,ansible_ansible_issues_41491
12474,12474.0,39.0,0.0,<!--- Paste example playbooks or commands between quotes below -->,ansible_ansible_issues_41491,12474.0,39.0,1.0,<!--- Paste example playbooks or commands between quotes below -->,ansible_ansible_issues_41491
12544,12544.0,5.0,1.0,"*Ray version and other system information (Python version, TensorFlow version, OS):* 2.0dev",ray-project_ray_issues_14577,12544.0,5.0,0.0,"*Ray version and other system information (Python version, TensorFlow version, OS):* 2.0dev",ray-project_ray_issues_14577
12592,12592.0,7.0,1.0,-->,home-assistant_core_issues_19191,12592.0,7.0,0.0,-->,home-assistant_core_issues_19191
12884,12884.0,9.0,1.0,-->,home-assistant_core_issues_23948,12884.0,9.0,0.0,-->,home-assistant_core_issues_23948
12894,12894.0,19.0,0.0,venv,home-assistant_core_issues_23948,12894.0,19.0,1.0,venv,home-assistant_core_issues_23948
12945,12945.0,10.0,1.0,- Using GPU in script?: Yes,huggingface_transformers_issues_9146,12945.0,10.0,0.0,- Using GPU in script?: Yes,huggingface_transformers_issues_9146
12946,12946.0,11.0,1.0,- Using distributed or parallel set-up in script?: Yes,huggingface_transformers_issues_9146,12946.0,11.0,0.0,- Using distributed or parallel set-up in script?: Yes,huggingface_transformers_issues_9146
13031,13031.0,96.0,0.0,2. Run `python run_glue.py --model_name_or_path roberta-large --do_train --do_eval --per_gpu_train_batch_size 8 --output_dir hypersearch-0 --task_name sst2 --evaluation_strategy steps --eval_steps 20 --logging_steps 10`,huggingface_transformers_issues_9146,13031.0,96.0,1.0,2. Run `python run_glue.py --model_name_or_path roberta-large --do_train --do_eval --per_gpu_train_batch_size 8 --output_dir hypersearch-0 --task_name sst2 --evaluation_strategy steps --eval_steps 20 --logging_steps 10`,huggingface_transformers_issues_9146
